### PR TITLE
Codec generated tool. Additional setters is added

### PR DESCRIPTION
**Pull request by alx-ut**
1. The generation of getters/setters by Enum is added to Decoder/Encoder generation tool.
For ex.
Encoder:
```java
    public NewOrderSingleEncoder ordType(OrdType value)
    {
        return ordType(value.representation());
    }
```
Decoder:
```java
    public OrdType ordTypeAsEnum()
    {
        return OrdType.decode(ordType);
    }
```
2. Type of representation of char type in generated Enum is changed from 'int' to 'char'
3. DictionaryAcceptor: 
- added default empty implementation to method
- added onUnknownMessage(int messageType) with empty default implementation

### CODE REVIEW

**Comment by mjpt777** [comment]
Can you provide a description of the what need this PR addresses?

**Comment by RichardWarburton** [comment]
I'm happy with most of these changes, But I would prefer to not have a default empty method for every acceptor method. If you want to have an easy way of overriding them I would prefer to generate an implementation class for the acceptor with empty implementatons of every method that someone could extend.

**Comment by alx-ut** [comment]
Agree. 
default keyword is removed from method signature.
Class DefaultDictionaryAcceptor with empty implementations is generated.

**Comment by alx-ut** [comment]
@mjpt777 :
The purpose of PR is to simplify usage of generated fix encoder/decoder:
- It's allow to use:
```java
newOrderSingleEncoder.ordType(OrdType.LIMIT) 
OrdType ordType = newOrderSingleDecoder.ordTypeAsEnum() 
```
invocations instead of 
```java
newOrderSingleEncoder.ordType((char)OrdType.LIMIT.representation()) 
OrdType ordType = OrdType.decode(newOrderSingleDecoder.ordType())
```
- DefaultDictionaryAcceptor  generation allow to override only desired message type acceptor instead of all one.

**Comment by RichardWarburton** [comment]
Thanks for the contribution.

**Pull request merged**
