### PR TITLE
Move iterator to interface for FIX Components

### PR DESCRIPTION
**Pull request by tom-smalls**
This change just affects FIX Components.

FIX Components have interfaces generated in artio to allow for re-use of code that handles the decoding of said Components. In the case of a FIX Component that contains a repeating group, the iterator for the repeating group currently lives on the various concrete implementations of the generated interface. This pull request moves the iterator implementation onto the interface as this will allow us to expose the iterator via the interface in the long run.

As part of this change, iterators now have a reference to their parent injected into them to allow for the iterator to be reset as this previously relied on being able to access internal fields.

### CODE REVIEW

**Comment by RichardWarburton** [comment]
@tom-smalls Having merge this PR I've just tried re-running the fix integration project and it does raise some compile errors, listed below. I think for now I'm just going to revert this change, I'd be happy to accept it, but it shouldn't cause compile errors in fix-integration. I have only just noticed when investigating now that fix-integration was pointing at the 0.18-snapshot version and not 0.19-snapshot, so you will have probably not seen these problems due to that issue.

```
> Task :fix-50-codecs:compileGeneratedJava
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityDefinitionUpdateReportDecoder.java:12737: error: incompatible types: SecurityDefinitionUpdateReportDecoder.MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private TickRulesGroupIterator tickRulesGroupIterator = new TickRulesGroupIterator(this);
                                                                                       ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityDefinitionUpdateReportDecoder.java:12772: error: incompatible types: SecurityDefinitionUpdateReportDecoder.MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private LotTypeRulesGroupIterator lotTypeRulesGroupIterator = new LotTypeRulesGroupIterator(this);
                                                                                                ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityTradingRulesDecoder.java:350: error: incompatible types: uk.co.real_logic.artio.decoder.BaseTradingRulesDecoder.TickRulesGroupDecoder cannot be converted to uk.co.real_logic.artio.decoder.SecurityTradingRulesDecoder.TickRulesGroupDecoder
            current = parent.tickRulesGroup();
                                           ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityTradingRulesDecoder.java:617: error: incompatible types: uk.co.real_logic.artio.decoder.BaseTradingRulesDecoder.LotTypeRulesGroupDecoder cannot be converted to uk.co.real_logic.artio.decoder.SecurityTradingRulesDecoder.LotTypeRulesGroupDecoder
            current = parent.lotTypeRulesGroup();
                                              ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityDefinitionDecoder.java:351: error: incompatible types: uk.co.real_logic.artio.decoder.DerivativeInstrumentDecoder.DerivativeSecurityAltIDGroupDecoder cannot be converted to uk.co.real_logic.artio.decoder.DerivativeSecurityDefinitionDecoder.DerivativeSecurityAltIDGroupDecoder
            current = parent.derivativeSecurityAltIDGroup();
                                                         ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityDefinitionDecoder.java:963: error: incompatible types: uk.co.real_logic.artio.decoder.DerivativeInstrumentDecoder.DerivativeEventsGroupDecoder cannot be converted to uk.co.real_logic.artio.decoder.DerivativeSecurityDefinitionDecoder.DerivativeEventsGroupDecoder
            current = parent.derivativeEventsGroup();
                                                  ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityDefinitionDecoder.java:1690: error: incompatible types: uk.co.real_logic.artio.decoder.DerivativeInstrumentDecoder.DerivativeInstrumentPartiesGroupDecoder cannot be converted to uk.co.real_logic.artio.decoder.DerivativeSecurityDefinitionDecoder.DerivativeInstrumentPartiesGroupDecoder
            current = parent.derivativeInstrumentPartiesGroup();
                                                             ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityDefinitionDecoder.java:2257: error: incompatible types: MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private TickRulesGroupIterator tickRulesGroupIterator = new TickRulesGroupIterator(this);
                                                                                       ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityDefinitionDecoder.java:2292: error: incompatible types: MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private LotTypeRulesGroupIterator lotTypeRulesGroupIterator = new LotTypeRulesGroupIterator(this);
                                                                                                ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListDecoder.java:3822: error: incompatible types: DerivativeSecurityListDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeSecurityAltIDGroupIterator derivativeSecurityAltIDGroupIterator = new DerivativeSecurityAltIDGroupIterator(this);
                                                                                                                                 ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListDecoder.java:5768: error: incompatible types: DerivativeSecurityListDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeEventsGroupIterator derivativeEventsGroupIterator = new DerivativeEventsGroupIterator(this);
                                                                                                            ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListDecoder.java:5803: error: incompatible types: DerivativeSecurityListDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeInstrumentPartiesGroupIterator derivativeInstrumentPartiesGroupIterator = new DerivativeInstrumentPartiesGroupIterator(this);
                                                                                                                                             ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityListUpdateReportDecoder.java:5594: error: incompatible types: SecurityListUpdateReportDecoder.RelatedSymGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private TickRulesGroupIterator tickRulesGroupIterator = new TickRulesGroupIterator(this);
                                                                                       ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityListUpdateReportDecoder.java:5629: error: incompatible types: SecurityListUpdateReportDecoder.RelatedSymGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private LotTypeRulesGroupIterator lotTypeRulesGroupIterator = new LotTypeRulesGroupIterator(this);
                                                                                                ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListUpdateReportDecoder.java:3783: error: incompatible types: DerivativeSecurityListUpdateReportDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeSecurityAltIDGroupIterator derivativeSecurityAltIDGroupIterator = new DerivativeSecurityAltIDGroupIterator(this);
                                                                                                                                 ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListUpdateReportDecoder.java:5729: error: incompatible types: DerivativeSecurityListUpdateReportDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeEventsGroupIterator derivativeEventsGroupIterator = new DerivativeEventsGroupIterator(this);
                                                                                                            ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/DerivativeSecurityListUpdateReportDecoder.java:5764: error: incompatible types: DerivativeSecurityListUpdateReportDecoder cannot be converted to DerivativeInstrumentDecoder
    private DerivativeInstrumentPartiesGroupIterator derivativeInstrumentPartiesGroupIterator = new DerivativeInstrumentPartiesGroupIterator(this);
                                                                                                                                             ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityDefinitionDecoder.java:12702: error: incompatible types: SecurityDefinitionDecoder.MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private TickRulesGroupIterator tickRulesGroupIterator = new TickRulesGroupIterator(this);
                                                                                       ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityDefinitionDecoder.java:12737: error: incompatible types: SecurityDefinitionDecoder.MarketSegmentsGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private LotTypeRulesGroupIterator lotTypeRulesGroupIterator = new LotTypeRulesGroupIterator(this);
                                                                                                ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityListDecoder.java:5477: error: incompatible types: SecurityListDecoder.RelatedSymGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private TickRulesGroupIterator tickRulesGroupIterator = new TickRulesGroupIterator(this);
                                                                                       ^
/home/richard/monotonic/fix-integration/fix-50-codecs/build/generated-src/uk/co/real_logic/artio/decoder/SecurityListDecoder.java:5512: error: incompatible types: SecurityListDecoder.RelatedSymGroupDecoder cannot be converted to BaseTradingRulesDecoder
    private LotTypeRulesGroupIterator lotTypeRulesGroupIterator = new LotTypeRulesGroupIterator(this);
```

**Comment by tom-smalls** [comment]
@RichardWarburton I haven't been able to replicate the problem unfortunately. `Fix42SpecAcceptanceTest.shouldPassAcceptanceCriteria[Acceptance: 14a_BadField.def` and `Fix42SpecAcceptanceTest.shouldPassAcceptanceCriteria[Acceptance: 14c_TagNotDefinedForMsgType.def` are failing locally for me on HEAD artio and fix-integration. Do you have the same problems?

**Comment by tom-smalls** [comment]
Please discard previous message, managed to re-produce locally.

So there are a few issues, and it's all around nesting (using `TickRules` in `FIX5.0SP2` as a example):

`TickRules` lives on both `RelatedSymGroup` and `BaseTradingRules` FIX Components. Artio ultimately will generate an iterator for `TickRulesDecoder` on each respective interface for these components. This isn't ideal as it doesn't solve the problem of code reuse for `TickRules` but believe can be solved by generating iterators and their decoders once in their own class file (depending on how complicated this is) rather than being nested.

The other problem is injecting the parent in order to reset the iterator with the number of elements in the group and first element in the linked  list. Generating one `TickRule` iterator cannot receive a parent as it has two different parents that do not share the same interface, hence the compilation errors. The only solution I can see for this is either to use the Supplier style interfaces or to add a class that represents the repeating group has a whole, not just the entries.

@RichardWarburton do you have any thoughts on this?

**Comment by RichardWarburton** [comment]
Thanks for looking into this @tom-smalls. I think you're right to go down the route of generating the `TickRuleDecoder` once in it's own file. I see the problem that results from this approach though.

Here's another idea: how about we go down the route of Supplier style interfaces, but using a specific interface, eg: `NoTickRulesSupplier` instead of using a generic `IntSupplier` interface. Part of the problem with the `IntSupplier` approach was that we ended using a method reference or a lambda passed in, which then results in another pointer indirection for the object that implements the method reference. Whereas a specific interface could just have an implementation that returns the int value from the field. Does that sound like a reasonable approach?

**Comment by tom-smalls** [comment]
That could work but ultimately depends on how hard it is to modify the
generated code!

Can you remember off the the top of your head why components that are just
repeating groups are inlined and not treated as components?

**Comment by RichardWarburton** [comment]
I can't I'm afraid. It might be worth doing a quick scan to see if there are any name collisions that result? That can sometimes happen with the FIX dictionary files - as this PR demonstrates.

**Comment by tom-smalls** [comment]
Commit says "fix naming overlaps between composites and groups, simplify
naming". However, I removed the method call for inlining and
fix-integration passes.

Its not a big deal, I just need a way if identifying repeating groups that
appear on components, which you don't know until after the inlining occurs.

On 10 Jan 2019 16:19, "Richard Warburton" <notifications@github.com> wrote:

I can't I'm afraid. It might be worth doing a quick scan to see if there
are any name collisions that result? That can sometimes happen with the FIX
dictionary files - as this PR demonstrates.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/real-logic/artio/pull/216#issuecomment-453156082>, or mute
the thread

**Comment by RichardWarburton** [comment]
Well that's good. Perhaps we've changed codegen approaches since then. To be honest I really can't remember.

**Pull request merged**
