### PR TITLE
minor fix for gradle config and logger disable

### PR DESCRIPTION
**Pull request by ghost**
remove repo in build.gradle to fix shadow plugin missing for fresh build
adding logger config checks in solo context to avoid NPE if logger is disabled.

### CODE REVIEW

**Comment by loveyoupeng** [comment]
sorry missed the readme, removed the repo from build.gradle

**Comment by RichardWarburton** [comment]
Cool, have you run the build and does it pass?

**Comment by loveyoupeng** [comment]
tried, failed due to some error caused by generation and style check, not sure the root cause, it pass clean install though.

pi@raspberrypi:~/Projects/opensources/artio $ ./gradlew 
:clean UP-TO-DATE
:artio-codecs:clean
:artio-core:clean
:artio-samples:clean
:artio-session-codecs:clean
:artio-session-fixt-codecs:clean
:artio-system-tests:clean
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:artio-codecs:compileJava
:artio-codecs:processResources
:artio-codecs:classes
:artio-codecs:generateMessages
:artio-codecs:compileGeneratedJava
:artio-codecs:processGeneratedResources NO-SOURCE
:artio-codecs:generatedClasses
:artio-codecs:jar
:artio-codecs:javadocJar
:artio-codecs:sourcesJar
:artio-codecs:compileTestJava
:artio-codecs:processTestResources
:artio-codecs:testClasses
:artio-codecs:testJar
:artio-codecs:assemble
:artio-codecs:checkstyleGenerated FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artio-codecs:checkstyleGenerated'.
> Unable to create Root Module: config {/home/pi/Projects/opensources/artio/config/checkstyle/checkstyle.xml}, classpath {/home/pi/Projects/opensources/artio/artio-codecs/build/classes/java/generated:/home/pi/Projects/opensources/artio/artio-codecs/build/resources/generated}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 17s
18 actionable tasks: 17 executed, 1 up-to-date

**Comment by RichardWarburton** [comment]
That's very strange. Running the build locally for me from master seems to pass ok. You don't happen to have changed any other files do you?

**Comment by loveyoupeng** [comment]
nothing, i build in rasberry pi, not sure if related.

**Comment by loveyoupeng** [comment]
tried clean build same error, seems related to "pi"

pi@raspberrypi:~/Projects/opensources/tmp $ git clone https://github.com/real-logic/artio.git
Cloning into 'artio'...
remote: Counting objects: 56689, done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 56689 (delta 141), reused 375 (delta 87), pack-reused 56214
Receiving objects: 100% (56689/56689), 7.12 MiB | 69.00 KiB/s, done.
Resolving deltas: 100% (23876/23876), done.
Checking connectivity... done.
pi@raspberrypi:~/Projects/opensources/tmp $ cd artio/
pi@raspberrypi:~/Projects/opensources/tmp/artio $ ./gradlew 
:clean UP-TO-DATE
:artio-codecs:clean UP-TO-DATE
:artio-core:clean UP-TO-DATE
:artio-samples:clean UP-TO-DATE
:artio-session-codecs:clean UP-TO-DATE
:artio-session-fixt-codecs:clean UP-TO-DATE
:artio-system-tests:clean UP-TO-DATE
:assemble UP-TO-DATE
:check UP-TO-DATE
:build UP-TO-DATE
:artio-codecs:compileJava
Download https://repo.maven.apache.org/maven2/org/agrona/agrona/0.9.16/agrona-0.9.16.pom
Download https://repo.maven.apache.org/maven2/uk/co/real-logic/sbe-tool/1.7.10/sbe-tool-1.7.10.pom
Download https://repo.maven.apache.org/maven2/org/agrona/agrona/0.9.16/agrona-0.9.16.jar
Download https://repo.maven.apache.org/maven2/uk/co/real-logic/sbe-tool/1.7.10/sbe-tool-1.7.10.jar
:artio-codecs:processResources
:artio-codecs:classes
:artio-codecs:generateMessages
:artio-codecs:compileGeneratedJava
:artio-codecs:processGeneratedResources NO-SOURCE
:artio-codecs:generatedClasses
:artio-codecs:jar
:artio-codecs:javadocJar
:artio-codecs:sourcesJar
:artio-codecs:compileTestJava
Download https://repo.maven.apache.org/maven2/org/mockito/mockito-core/2.18.3/mockito-core-2.18.3.pom
Download https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.pom
Download https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy-parent/1.8.5/byte-buddy-parent-1.8.5.pom
Download https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.pom
Download https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy-agent/1.8.5/byte-buddy-agent-1.8.5.jar
Download https://repo.maven.apache.org/maven2/org/mockito/mockito-core/2.18.3/mockito-core-2.18.3.jar
Download https://repo.maven.apache.org/maven2/net/bytebuddy/byte-buddy/1.8.5/byte-buddy-1.8.5.jar
:artio-codecs:processTestResources
:artio-codecs:testClasses
:artio-codecs:testJar
:artio-codecs:assemble
:artio-codecs:checkstyleGenerated FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':artio-codecs:checkstyleGenerated'.
> Unable to create Root Module: config {/home/pi/Projects/opensources/tmp/artio/config/checkstyle/checkstyle.xml}, classpath {/home/pi/Projects/opensources/tmp/artio/artio-codecs/build/classes/java/generated:/home/pi/Projects/opensources/tmp/artio/artio-codecs/build/resources/generated}.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 46s
18 actionable tasks: 11 executed, 7 up-to-date

**Comment by RichardWarburton** [comment]
@loveyoupeng - btw if you take a look at `artio-codecs/build/reports/checkstyle/generated.html` or `artio-codecs/build/reports/checkstyle/generated.xml` then it should tell you what the checkstyle errors are. I'm happy to help diagnose things if you'll let me know what the problems are.

**Pull request merged**
