### PR TITLE
change TcpChannelSupplier from class to interface

### PR DESCRIPTION
**Pull request by alx-ut**
interface is extracted from TcpChannelSupplier.
Existing implementation are moved to DefaultTcpChannelSupplier

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Thanks for the PR but being a class enables the JIT compiler to make class hierarchy analysis based optimizations. What's the motivation for this change?

**Comment by alx-ut** [comment]
We need to turn on/off listening socket by schedule and have filtering by IP address.
May be better leave to TcpChannelSupplier as a class and allow to extend listeningChannel behavior via additional policy?

**Comment by RichardWarburton** [comment]
I think it's fine for your to just implement your own TcpChannelSupplier without me doing that. The thing is that if I expose those fields then I'm exposing implementation detail of that class and committing to it for you. If I change the implementation, even for example renaming a field, then I might break your subclass. You're better off to just copy the code a bit more and not coupling an external implementation to this class.

Also - if you just want to filter by IP address you don't need to do it by changing Artio at all - you could just add an `iptables` rule.

**Comment by alx-ut** [comment]
Agree. 
That's the reason of separation between interface(abstract class) and default implementation.

How TcpChannelSupplier can be created without listeningChannel bind in constructor? 
The only solution now - is invoke super() with the specific EngineConfiguration clone without bindAddress.

The copy of the whole class is valid.

iptables exists, but the accepted addresses should should be also controlled by java code.

**Comment by RichardWarburton** [comment]
Maybe an alternative refactor would be to switch the interface to an abstract class? That way you would get the separation that you want but the class hierarchy analysis would also work.

**Comment by alx-ut** [comment]
Agree. 
Change TcpChannelSupplier to abstract class with empty constructor is fine. 
The existing implementation will be moved to DefaultTcpChannelSupplier.
Or it's better to leave existing implementation in TcpChannelSupplier and introduce class AbstractTcpChannelSupplier?

**Comment by RichardWarburton** [comment]
I think better to change the TcpChannelSupplier to an abstract class and add a DefaultTcpChannelSupplier.

**Pull request closed without merging**
