### PR TITLE
System property for configuring enum values

### PR DESCRIPTION
**Pull request by tom-smalls**
Use the fix.codecs.disable_reject_unknown_enum_value system property
to disable enum value validation. This maintains the default behaviour
of rejecting if an unknown enum value is received but now gives the
option of to opt out of this.

We've found that venues will add new enum values without warning,
which we don't want to reject on. If we don't support the enum value
then we can just ignore it rather than rejecting the whole
fix message

### CODE REVIEW

**Comment by tom-smalls** [comment]
Wasn't sure if it was best to do this as runtime system property or at compile time

**Comment by RichardWarburton** [comment]
Looks good. I think runtime is fine because with a static final field then its possible to optimize it out. Thanks for the PR.

**Comment by RichardWarburton** [comment]
Looks good. I think runtime is fine because with a static final field then its possible to optimize it out. Thanks for the PR.

**Comment by tom-smalls** [comment]
I have one more commit for this but can't push as GitHub seems to be upset

**Pull request merged**
