### PR TITLE
Encoder getters fields for STRING, TIMESTAMP field types

### PR DESCRIPTION
**Pull request by alx-ut**
Added getters fields to Encoder for STRING, TIMESTAMP field types.

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Hi, thanks for the PR. Have you run the build and also checked the fix integration tests as well? https://github.com/real-logic/fix-integration

**Comment by RichardWarburton** [comment]
Please don't add jcenter to the build.gradle file. Some people use internal nexus or maven repositories to deploy software into and are banned from using jcenter. If you need to depend on jcenter please follow the instructions in the README on setting up init.gradle.

**Comment by alx-ut** [comment]
Fix integration tests passed
fix-integration>gradle clean build
...
Test in BUILD SUCCESSFUL in 3m 2s

**Comment by RichardWarburton** [comment]
Great, thanks.

**Pull request merged**
