### PR TITLE
Do not match subsequences when matching headers

### PR DESCRIPTION
**Pull request by wojciech-adaptive**
Header predicate for foobar will match foo, but I believe that should be exact.

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Hi Wojciech,

I think the bug you've found is a good spot but shouldn't it be fixed in the following method in `CodecUtil`?

```public static boolean equals(
        final char[] value,
        final char[] expected,
        final int offset,
        final int expectedOffset,
        final int length)```

**Comment by RichardWarburton** [comment]
Because you've fixed it for the predicate here but the same problem exists elsewhere.

**Comment by wojciech-adaptive** [comment]
I considered that, but it seemed like this method is more generic and can compare arbitrary subsequences, so there's no way to get expected length unless we add a new parameter.

Looking again at this method, shouldn't it be using offsets in the length check?

**Comment by RichardWarburton** [comment]
Yeah, I think it should.

**Comment by RichardWarburton** [comment]
Thanks.

**Pull request merged**
