### PR TITLE
extend unbind operation with optional disconnect and logout

### PR DESCRIPTION
**Pull request by vdaniloff**
Actually I think EndOfDay is already an out of date name for a command, so probably this has to be renamed as well.

### CODE REVIEW

**Comment by RichardWarburton** [comment]
Thanks for the PR @vdaniloff .

The only thing that I'm not so sure of here when reviewing this code is what happens if you call unbind and then bind immediately after one another. This didn't used to be a problem because the entire `unbind()` operation within the Framer was only one step on its duty cycle - so unbind and bind wouldn't race. Now unbind has multiple steps because its waiting for the logouts to happen.

I'm not 100% sure what the right behaviour here is either.
1) Would we just want the bind operation to throw an exception?
2) Should it wait until every existing connection is logged out and then rebind the backing port.
3) Should it stop the unbind?

I think (3) seems really hard to reason about - if some sessions got logged out and others didn't. So I think either (1) or (2) is best. But I think we should be clear about the semantics and not end up with a race condition.

**Comment by vdaniloff** [comment]
Good question! Actually I am also not sure what would be expected, 1) is definitely easier to implement, so I will add this.

**Comment by vdaniloff** [comment]
done, if ever need to switch to 2) then polling the pending reply can be added as a step in unitofwork.

**Comment by RichardWarburton** [comment]
Thanks - I'm merging this in - I'll cleanup the success() statements myself and I've also realised we've got some similar undefined behaviour with two unbind operations that I'll fixup.

**Pull request merged**
